todoproject/todoapp/urls.py
from django.urls import path
from.import views
app_name='todoapp'
urlpatterns = [

    path('',views.home,name='home'),
    path('delete/<int:id>/',views.delete,name='delete'),
    path('update/<int:id>/',views.update,name='update')
    # path('details/',views.details,name='details')
]

todoproject/todoproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('todoapp.urls'))
]

if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,
                         document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT)

todoproject/todoapp/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    name=models.CharField(max_length=250)
    priority=models.IntegerField()
    date=models.DateField()
    def __str__(self):
        return self.name

todoproject/todoapp/forms.py
from django import forms
from . models import Task

class Todoform(forms.ModelForm):
    class Meta:
        model=Task
        fields=['name','priority','date']

todoproject/todoapp/views.py
from django.shortcuts import render, redirect
from.models import Task
from.forms import Todoform
# Create your views here.

def home(request):
    task1 = Task.objects.all()
    if request.method=='POST':
        name=request.POST.get('task','')
        priority=request.POST.get('priority','')
        date=request.POST.get('date','')
        task=Task(name=name,priority=priority,date=date)
        task.save()
    return render(request,'home.html',{'task':task1})
# def details(request):
#
#     return render(request,'details.html',{'task':task})
def delete(request,id):
    if request.method=='POST':
        task=Task.objects.get(id=id)
        task.delete()
        return redirect('/')
    return render(request,'delete.html')
def update(request,id):
    task=Task.objects.get(id=id)
    form=Todoform(request.POST or None,instance=task)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'task':task})

todoproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
{% block body %}
{% endblock %}
</body>
</html>

todoproject/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="POST">
    {% csrf_token %}
    <P>Are you done with task?</P>
    <input type="submit">
</form>
{% endblock %}

todoproject/templates/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for i in task %}
{{i.name}}
{{i.priority}}
{% endfor %}
</body>
</html>

todoproject/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<form method="POST">
    {% csrf_token %}
  {{form.as_p}}

  <button type="submit">confirm</button>
</form>
{% endblock %}

todoproject/templates/home.html
{% extends 'base.html' %}
{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="banner">
                <div class="banner-text">
                    <h1>todo</h1>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <form method="post" class="p-3 shadow">
                {% csrf_token %}
                <div class="form-group">
                        <input type="text" class='form-control' name="task" placeholder="enter the task">

                </div>
                <div class="form-group">
                        <input type="text" class="form-control" name="priority" placeholder="enter priority">

                </div>
                   <div class="form-group">
                        <input type="date" class="form-control" name="date" >

                </div>
                <input type="submit" class="btn btn-success">
            </form>
        </div>
        <div class="col-md-6">
            <h4>Task to be completed</h4>
             {% for i in task %}
            <div class="shadow card">
                <div class="card-body">
                    <h5 class="card-title">{{i.name}}</h5>
                    <p><b>{{i.priority}}</b></p>
                    <p><b>{{i.date}}</b></p>
                    <a href="{% url 'todoapp:delete' i.id %}" class="btn btn-danger">Done</a>
                    <a href="{% url 'todoapp:update' i.id %}" class="btn btn-primary">update</a>

                </div>
            </div>
            <br>
            {% endfor %}
        </div>

    </div>



</div>
{% endblock %}